require("config.general")
require("config.telescope")
require("config.treesitter")
require("config.langserver")
require("config.theme")
require("config.cmds")
require("config.formatter")
require("config.discord")
