return {
	{ 'ibhagwan/fzf-lua' },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ 'neovim/nvim-lspconfig'},
	{ 'nvimdev/lspsaga.nvim' },
	{ 'ms-jpq/coq_nvim' },
	{ 'ms-jpq/coq.artifacts' },
	{
		'ms-jpq/coq.thirdparty',
		branch = '3p'
	},
	{ 'nanozuki/tabby.nvim' },
	{ 'nvim-treesitter/nvim-treesitter' },
	{ 'nvim-treesitter/playground' },
	{ 'MDeiml/tree-sitter-markdown' },
	{ 'glepnir/dashboard-nvim' },
	{ 'numToStr/Comment.nvim' },
	{ 'kylechui/nvim-surround' },
	{ 'windwp/nvim-autopairs' },
	{ "MunifTanjim/nui.nvim" },
	{ "nvim-lua/plenary.nvim" },
	{ "nacro90/numb.nvim" },
	{ "nvim-telescope/telescope.nvim" },
	{ "sindrets/diffview.nvim" },
	{ 'Vimjas/vim-python-pep8-indent' },
	{ "catppuccin/nvim", as = "catppuccin" },
	{ "Shatur/neovim-ayu" },
	{ "ellisonleao/gruvbox.nvim" },
	{ "folke/tokyonight.nvim" },
	{ "UtkarshVerma/molokai.nvim" },
	{ "cpea2506/one_monokai.nvim" },
	{ "sonph/onehalf" },
	{ "nvim-tree-web-devicons" },
	{ "SmiteshP/nvim-navic" },
	{ "utilyre/barbecue.nvim" },
	{ "nvim-lualine/lualine.nvim" },
	{ "yorickpeterse/nvim-window" },
	{ "andweeb/presence.nvim" }
}
